name: Android CI

on:
  pull_request:  
  workflow_dispatch:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        
      - name: set up JDK 21
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
        with:
           allow-snapshot-wrappers: true
      
      - name: Build apk
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease -Darch=arm64 --configuration ksp

      - name: Upload apk
        uses: actions/upload-artifact@main
        with:
          name: app-debug-arm64
          path: |
                **/*.apk
