name: Android CI

on:
  push:
  workflow_dispatch:

jobs:
  Build:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/build.yml
    with:
      variant: Release
    secrets:
      CRYPTO_KEY: ${{ secrets.CRYPTO_KEY }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}

  Build-Debug:
    uses: ./.github/workflows/build.yml
    with:
      variant: Debug
